### ISSUE TITLE
Leofs_gateway do not response or return HTTP error code 5xx

### ISSUE THREAD

**Issue by minhchuduc** [leo-project/leo_gateway#15]
Environments:
Leofs version 1.2.6, installed using .deb file
Erlang R16B03-1 (erts-5.10.4) [source] [64-bit halfword] [smp:16:16] [async-threads:10] [kernel-poll:false]
Ubuntu 14.04 on Baremetal
Kernel 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 GNU/Linux

On a terminal i run stress test:
<pre>siege -c 500 -r 2 http://hehe1.s3.mydomain.com/300MB_file</pre>

On another terminal i download some small file to test its responsiveness:
<pre>wget http://hehe1.s3.mydomain.com/IMAGES/0478e05a-d5e5-47ac-bab9-26278a2de1ec.jpg</pre>

And i receive 3 types of response randomly:

1: OK

<pre> (it delay a bit, sometimes quite long, then...)
Saving to: `0478e05a-d5e5-47ac-bab9-26278a2de1ec.jpg.13'

100%[======================================================================================================>] 229,449     --.-K/s   in 0.002s

2015-03-04 13:44:10 (115 MB/s) - `0478e05a-d5e5-47ac-bab9-26278a2de1ec.jpg.13' saved [229449/229449]</pre>

Download time is "0.002s"
It's mean Time to first byte is so long (http://en.wikipedia.org/wiki/Time_To_First_Byte)
--
--

2: ERROR 503: Service Unavailable

<pre>...
HTTP request sent, awaiting response... 503 Service Unavailable
2015-03-04 13:44:11 ERROR 503: Service Unavailable.
</pre>

--

3: ERROR 500: Internal Server Error

<pre>...
HTTP request sent, awaiting response... 500 Internal Server Error
2015-03-04 13:45:20 ERROR 500: Internal Server Error.
</pre>

Output of my "leofs-adm status gateway_0@172.x.y.z":
<pre>
-------------------------------+------------------
             Item              |       Value
-------------------------------+------------------
 Config-1: basic
--------------------------------------------------
 [basic]
-------------------------------+------------------
                       version | 1.2.6
                using protocol | s3
                       log dir | ./log/erlang
-------------------------------+------------------
 [http server related for rest/s3 api]
-------------------------------+------------------
                listening port | 80
            listening ssl port | 443
           number of_acceptors | 256
-------------------------------+------------------
 [cache-related]
-------------------------------+------------------
       http cache [true|false] | false
       number of cache_workers | 16
                  cache expire | 600
         cache max content len | 3123456789
            ram cache capacity | 6123456789
        disk cache capacity    | 30123456789
        disk cache threshold   | 20123456
        disk cache data dir    | ./cache/data
        disk cache journal dir | ./cache/journal
-------------------------------+------------------
 [large object related]
-------------------------------+------------------
      max number of chunk objs | 1000
           chunk object length | 5242880
             max object length | 5242880000
     reading  chunk obj length | 5242880
     threshold of chunk length | 5767168
-------------------------------+------------------
 Config-2: watchdog
-------------------------------+------------------
 [rex(rpc-proc)]               |
             watch interval(s) | 5
        threshold mem capacity | 335544320
-------------------------------+------------------
 [cpu]                         |
              watchdog eanbled | disabled
             watch interval(s) | 5
        threshold cpu load avg | 5.0
         threshold cpu util(%) | 100
-------------------------------+------------------
 [io]                          |
              watchdog enabled | enabled
             watch interval(s) | 1
        threshold input size/s | 134217728
       threshold output size/s | 134217728
-------------------------------+------------------
 Status-1: RING hash
-------------------------------+------------------
             current ring hash | 9d2edfe6
            previous ring hash | 9d2edfe6
-------------------------------+------------------
 Status-2: Erlang VM
-------------------------------+------------------
                    vm version | 5.10.4
               total mem usage | 75322280
              system mem usage | 54630464
               procs mem usage | 20690424
                 ets mem usage | 5585976
                         procs | 728/1048576
                   kernel_poll | true
              thread_pool_size | 32
-------------------------------+------------------
</pre>

**Comment by yosukehara** [comment]
Thank you for your report. We'd like to know your environments and system information to check this issue. I've put partial of LeoFS's issue template as follows. It would be nice if you answer them.

### Environments
* What version of Erlang are you using?
* What kind of virtualization(VMWare/Docker/Xen...) are you using or using Baremetal?

### System information
* Attach the result of issueing a status command(leofs-adm status).
* Attach the result of issueing a status command to a specific node(leofs-adm status $nodename) as necessary.
* Attach error log files if that exists.

**Comment by yosukehara** [comment]
In this situation, it seems the storage nodes become very high-load because of retrieving chunk objects of a large-object and also, network traffic may be very high between the gateway and the storage node(s).

We'd like to know the watchdog configuration of the gateway-node and the storage-node(s).

* Reference: 
    * [Watchdog](http://leo-project.net/leofs/docs/configuration/configuration_7.html)

**Comment by minhchuduc** [comment]
Hi sorry, i will update my issue and move it to LeoFS repo.
