### ISSUE TITLE
gateway error-miss files

### ISSUE THREAD

**Issue by weiransoft** [leo-project/leo_gateway#34]
Hi, I have deployed LEOFS in my server over 1 year.but I found an issue that  lost a lots of files at recent week. there are error log in gateway log file. 

[E]     gateway_0@127.0.0.1     2015-12-14 22:08:02.779466 +0800        1450102082      null:null       0       Error in process <0.18920.0> on node 'gateway_0@127.0.0.1' with exit value: {{try_clause,{ok,{http_req,#Port<0.8708>,ranch_tcp,close,<0.18920.0>,<<3 bytes>>,'HTTP/1.0',{{172,16,91,8},36929},<<12 bytes>>,undefined,8082,<<1 byte>>,undefined,<<0 bytes>>,undefined,[],[{<<4 bytes>>,<<17 bytes>>},{<<10 bytes>>,<<5 bytes>>},{<<6 bytes>>,<<78 bytes>>},{<<14 bytes>>,<<22 bytes>>},{<<15 bytes>>,<<12 bytes>>},{<<4 bytes>>,<<69 bytes>>},{<<10 bytes>>,<<88 bytes>>}],[{<<10 bytes>>,[<<5 bytes>>]}],undefined,[],waiting,<<0 bytes>>,undefined,false,done,[],<<0 bytes>>,undefined}}},[{cowboy_handler,handler_handle...

[E]     gateway_0@127.0.0.1     2015-12-14 22:08:02.823175 +0800        1450102082      null:null       0       Error in process <0.18924.0> on node 'gateway_0@127.0.0.1' with exit value: {{try_clause,{ok,{http_req,#Port<0.8711>,ranch_tcp,close,<0.18924.0>,<<3 bytes>>,'HTTP/1.0',{{172,16,91,8},36933},<<12 bytes>>,undefined,8082,<<1 byte>>,undefined,<<0 bytes>>,undefined,[],[{<<4 bytes>>,<<17 bytes>>},{<<10 bytes>>,<<5 bytes>>},{<<6 bytes>>,<<78 bytes>>},{<<14 bytes>>,<<22 bytes>>},{<<15 bytes>>,<<12 bytes>>},{<<4 bytes>>,<<69 bytes>>},{<<10 bytes>>,<<88 bytes>>}],[{<<10 bytes>>,[<<5 bytes>>]}],undefined,[],waiting,<<0 bytes>>,undefined,false,done,[],<<0 bytes>>,undefined}}},[{cowboy_handler,handler_handle...

[E]     gateway_0@127.0.0.1     2015-12-14 22:08:02.896222 +0800        1450102082      null:null       0       Error in process <0.18925.0> on node 'gateway_0@127.0.0.1' with exit value: {{try_clause,{ok,{http_req,#Port<0.8712>,ranch_tcp,close,<0.18925.0>,<<3 bytes>>,'HTTP/1.0',{{172,16,91,8},36936},<<12 bytes>>,undefined,8082,<<1 byte>>,undefined,<<0 bytes>>,undefined,[],[{<<4 bytes>>,<<17 bytes>>},{<<10 bytes>>,<<5 bytes>>},{<<6 bytes>>,<<78 bytes>>},{<<14 bytes>>,<<22 bytes>>},{<<15 bytes>>,<<12 bytes>>},{<<4 bytes>>,<<69 bytes>>},{<<10 bytes>>,<<88 bytes>>}],[{<<10 bytes>>,[<<5 bytes>>]}],undefined,[],waiting,<<0 bytes>>,undefined,false,done,[],<<0 bytes>>,undefined}}},[{cowboy_handler,handler_handle...

**Comment by yosukehara** [comment]
Thank you for your report. We'd like to know the detail to check this issue. It would be nice, if you write the detail with (Template of an issue report)[https://github.com/leo-project/leofs/wiki/issue-report-template].

**Comment by weiransoft** [comment]
[erl_creash-dump.zip](https://github.com/leo-project/leo_gateway/files/61995/erl_creash-dump.zip)

**Comment by weiransoft** [comment]
What purpose of LeoFS do you use?
Production

What version of LeoFS are you using?
1.2.3
What version of Erlang are you using?
Erlang/OTP 17 [erts-6.3] [source] [64-bit halfword] 
What kind of virtualization(VMWare/Docker/Xen...) are you using or using Baremetal?
VMWare 
What operating system(uname -a) and processor architecture(cat /proc/cpuinfo) and memory(cat /proc/meminfo) are you using?

Linux DMZ2-ESHOP-Img-12 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Intel(R) Xeon(R) CPU E5-2650 X4
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 45
model name      : Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping        : 7
microcode       : 0x710
cpu MHz         : 2000.000
cache size      : 20480 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 popcnt aes xsave avx hypervisor lahf_lm ida arat pln pts dtherm
bogomips        : 4000.00
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management

What happened and How to reproduce if possible

It can't find same files as I reported.
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>

System information

Attach the result of issueing a status command(leofs-adm status).
[System Confiuration]
---------------------------------+----------
 Item                            | Value
---------------------------------+----------
 Basic/Consistency level
---------------------------------+----------
                  system version | 1.2.3
                      cluster Id | leofs_1
                           DC Id | dc_1
                  Total replicas | 1
        number of successes of R | 1
        number of successes of W | 1
        number of successes of D | 1
 number of DC-awareness replicas | 0
                       ring size | 2^128
---------------------------------+----------
 Multi DC replication settings
---------------------------------+----------
      max number of joinable DCs | 2
         number of replicas a DC | 1
---------------------------------+----------
 Manager RING hash
---------------------------------+----------
               current ring-hash | be555c82
              previous ring-hash | be555c82
---------------------------------+----------

 [State of Node(s)]
-------+--------------------------+--------------+----------------+----------------+----------------------------
 type  |           node           |    state     |  current ring  |   prev ring    |          updated at
-------+--------------------------+--------------+----------------+----------------+----------------------------
  S    | storage_0@127.0.0.1      | running      | be555c82       | be555c82       | 2015-12-10 18:14:52 +0800
  G    | gateway_0@127.0.0.1      | running      | be555c82       | be555c82       | 2015-12-14 21:47:51 +0800
-------+--------------------------+--------------+----------------+----------------+----------------------------

Attach the result of issueing a status command to a specific node(leofs-adm status $nodename) as necessary.
Attach command histories.(history|grep leofs-adm)
 1105  leofs-adm create-user admin Mini1234
 1531  leofs-adm start
 1532  leofs-adm status
//I found same files can't found ,and used the recover comcand 
 1628  leofs-adm recover-node storage@127.0.0.1
 1629  leofs-adm recover-node storage_0@127.0.0.1
 1630  leofs-adm recover-node storage_~@127.0.0.1
 1631  leofs-adm recover-node storage_1@127.0.0.1
 1632  leofs-adm recover-ring storage_0@127.0.0.1
 1633  leofs-adm recover-cluster cluster-1
 1764  leofs-adm status storage_0@127.0.0.1
 1875  leofs-adm recover-node storage_0@127.0.0.1
 1894  leofs-adm cluster-status
 1895  leofs-adm status
 1989  leofs-adm status
 1990  history|grep leofs-adm

Attach configuration files(leo_(gateway|storage|manager).conf) as necessary.
I used the configration

**Comment by yosukehara** [comment]
I've checked the crash-dump w/Erlang's crashdump_viewer:
![erlang-crashdump-viewer-34](https://cloud.githubusercontent.com/assets/148770/11801630/149448fe-a32b-11e5-8646-5ef28d0aa883.jpg)

And then, I've recognized it seems memory leak happened at the gateway.
I recommend two things as below:

* Upgrade Erlang's version to [Erlang 17.5](http://www.erlang.org/download_release/28)
* Upgrade LeoFS to [v1.2.16](https://github.com/leo-project/leofs/releases/tag/1.2.16), which is the latest and stable version.


Furthermore, you can check whether the files exist or not with [leofs-adm whereis command](http://leo-project.net/leofs/docs/admin_guide/admin_guide_2.html#whereis-command).

**Comment by weiransoft** [comment]
Thanks for your help.
I got message with use leofs-adm whereis :
root@DMZ2-ESHOP-Img-12:/usr/local/leofs/1.2.3# leofs-adm whereis images/upload/store/8/abd0c8ce-13b2-422b-874f-cdb05d525a25.jpg_small.jpg
-------+--------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------------------
 del?  |           node           |             ring address             |    size    |   checksum   |  # of chunks   |     clock      |             when 
-------+--------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------------------
       | storage_0@127.0.0.1      | c554734c9df40d184e6e9b82b5e9990b     |         6K |   30cfbecde4 |              0 | 513735b72d159  | 2015-04-11 22:04:19 +0800

root@DMZ2-ESHOP-Img-12:/usr/local/leofs/1.2.3# leofs-adm whereis images/upload/zhiku/titleImage/1441770482634_e1dd6433-4ea7-4534-9452-468bc31bc746.jpg
-------+--------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------------------
 del?  |           node           |             ring address             |    size    |   checksum   |  # of chunks   |     clock      |             when 
-------+--------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------------------
  *    | storage_0@127.0.0.1      | 4b8d0eaa0e0f3708a007fdb864ad0656     |         0B |   d41d8cd98f |              0 | 52695c961f143  | 2015-12-11 10:07:34 +0800

so that you can see the images/upload/store/8/abd0c8ce-13b2-422b-874f-cdb05d525a25.jpg_small.jpg is exist so its size is 6K, the other one not exist because that's size is 0B.

**Comment by yosukehara** [comment]
`` images/upload/zhiku/titleImage/1441770482634_e1dd6433-4ea7-4534-9452-468bc31bc746.jpg`` is removed because it has a delete-flag,``del?``, 1st column of the result.

**Comment by weiransoft** [comment]
it's hard to find out who delete the files ,so there is any command can recover the file which deleted by mistake.

**Comment by weiransoft** [comment]
In fact,I checked the access log, there is not any delete request with abd0c8ce-13b2-422b-874f-cdb05d525a25.jpg_small.jpg, have any command to know the delete request log in LEOFS?

**Comment by yosukehara** [comment]
You can only know the log from the access-log, which means we deliver another solution.

**Comment by yosukehara** [comment]
In addition, we've found one issue on LeoFS's issue:
[#384 [leo_gateway] Some access logs have been not recorded](https://github.com/leo-project/leofs/issues/384)

**Comment by weiransoft** [comment]
yeah,thanks for your comment,I'm ready to upgrade my production version ,and I would like know how to recover the files that deleted by mistake.

**Comment by weiransoft** [comment]
The lost files issue happened again in last night， unfortunately ，access log files of leofs and my nginx access log not found any delete request. :-(

**Comment by yosukehara** [comment]
Do you have any error logs of the LeoFS' Gateway, Storage node and other such as syslog?
Are you able to access the gateway with a s3-client? You're able to know current status w/``leofs-adm status`` command.

**Comment by weiransoft** [comment]
leofs-adm status
 [System Confiuration]
---------------------------------+----------
 Item                            | Value
---------------------------------+----------
 Basic/Consistency level
---------------------------------+----------
                  system version | 1.2.3
                      cluster Id | leofs_1
                           DC Id | dc_1
                  Total replicas | 1
        number of successes of R | 1
        number of successes of W | 1
        number of successes of D | 1
 number of DC-awareness replicas | 0
                       ring size | 2^128
---------------------------------+----------
 Multi DC replication settings
---------------------------------+----------
      max number of joinable DCs | 2
         number of replicas a DC | 1
---------------------------------+----------
 Manager RING hash
---------------------------------+----------
               current ring-hash | be555c82
              previous ring-hash | be555c82
---------------------------------+----------

 [State of Node(s)]
-------+--------------------------+--------------+----------------+----------------+----------------------------
 type  |           node           |    state     |  current ring  |   prev ring    |          updated at
-------+--------------------------+--------------+----------------+----------------+----------------------------
  S    | storage_0@127.0.0.1      | running      | be555c82       | be555c82       | 2015-12-10 18:14:52 +0800
  G    | gateway_0@127.0.0.1      | running      | be555c82       | be555c82       | 2015-12-15 16:46:52 +0800
-------+--------------------------+--------------+----------------+----------------+----------------------------

**Comment by yosukehara** [comment]
Actually, LeoFS does not remove objects automatically except the data-compaction.
As I mentioned, there was an issue of the delete-log output in v1.2.3:
> In addition, we've found one issue on LeoFS's issue:
> #384 [leo_gateway] Some access logs have been not recorded

In addition, you does not configure redundancy of a object, which means the total replicas is one. So LeoFS ignore ``leofs-adm recover-*`` commands. 

> Total replicas | 1

Do you think you could check your environment?

**Comment by weiransoft** [comment]
I use REST to put files, not use the S3-client.

And I use the 
leofs-adm recover-node storage_0@127.0.0.1
leofs-adm recover-ring storage_0@127.0.0.1
leofs-adm recover-cluster cluster-1

but the lost files are still miss..

**Comment by yosukehara** [comment]
There is no cluster in your environment, which means ``recover-*`` is ignored
You could read the getting started's note as below:
* [Quick Start: All in one in a local node](http://leo-project.net/leofs/docs/getting_started/getting_started_1.html)
    * NOTE: 
In this section, LeoFS Storage, LeoFS Gateway and LeoFS Manager are all installed on a single system, **with no clustering**.

**Comment by weiransoft** [comment]
I found some error log in storage 


[E]     storage_0@127.0.0.1     2015-12-10 17:35:08.136977 +0800        1449740108      null:null       0       gen_server leo_object_storage_1 terminated with reason: {timeout,{gen_server,call,[leo_metadata_1,close,30000]}}
[E]     storage_0@127.0.0.1     2015-12-10 17:35:08.139045 +0800        1449740108      null:null       0       ["CRASH REPORT ",[80,114,111,99,101,115,115,32,"leo_object_storage_1",32,119,105,116,104,32,"0",32,110,101,105,103,104,98,111,117,114,
115,32,"exited",32,119,105,116,104,32,114,101,97,115,111,110,58,32,[[123,["timeout",44,[123,["gen_server",44,"call",44,[91,["leo_metadata_1",44,"close",44,"30000"],93]],125]],125]," in ",[["gen_server",58,"terminate",47,"6"],[32,108,105,110,101,3
2,"722"]]]]]
[E]     storage_0@127.0.0.1     2015-12-10 17:35:08.141282 +0800        1449740108      null:null       0       Supervisor leo_object_storage_sup had child leo_object_storage_1 started with leo_object_storage_server:start_link(leo_object_storage_
1, 1, leo_metadata_1, leo_compact_worker_1, leo_diagnosis_log_1, "/usr/local/leofs/1.2.3/leo_storage/avs/", false) at <0.209.0> exit with reason {timeout,{gen_server,call,[leo_metadata_1,close,30000]}} in context child_terminated
[E]     storage_0@127.0.0.1     2015-12-10 17:35:08.142586 +0800        1449740108      null:null       0       gen_server leo_object_storage_2 terminated with reason: {timeout,{gen_server,call,[leo_metadata_2,close,30000]}}
[E]     storage_0@127.0.0.1     2015-12-10 17:35:08.144031 +0800        1449740108      null:null       0       ["CRASH REPORT ",[80,114,111,99,101,115,115,32,"leo_object_storage_2",32,119,105,116,104,32,"0",32,110,101,105,103,104,98,111,117,114,
115,32,"exited",32,119,105,116,104,32,114,101,97,115,111,110,58,32,[[123,["timeout",44,[123,["gen_server",44,"call",44,[91,["leo_metadata_2",44,"close",44,"30000"],93]],125]],125]," in ",[["gen_server",58,"terminate",47,"6"],[32,108,105,110,101,3
2,"722"]]]]]
[E]     storage_0@127.0.0.1     2015-12-10 17:35:08.267117 +0800        1449740108      null:null       0       Supervisor leo_object_storage_sup had child leo_object_storage_2 started with leo_object_storage_server:start_link(leo_object_storage_
2, 2, leo_metadata_2, leo_compact_worker_2, leo_diagnosis_log_2, "/usr/local/leofs/1.2.3/leo_storage/avs/", false) at <0.193.0> exit with reason {timeout,{gen_server,call,[leo_metadata_2,close,30000]}} in context child_terminated
[E]     storage_0@127.0.0.1     2015-12-10 17:35:50.644867 +0800        1449740150      leo_backend_db_bitcask:get/2    98      {invalid_ref,#Ref<0.0.0.120551>}
[W]     storage_0@127.0.0.1     2015-12-10 17:35:50.645729 +0800        1449740150      leo_storage_handler_object:read_and_repair_2/3  935     key:<<"images/upload/zhiku/advert/1441858518864_354a3449-c4e0-41af-a3b7-41f117c78e99.jpg">>, cause:{in
valid_ref,#Ref<0.0.0.120551>}
[W]     storage_0@127.0.0.1     2015-12-10 17:35:50.647131 +0800        1449740150      leo_storage_handler_object:read_and_repair_2/3  935     key:<<"images/upload/zhiku/transitionPage/1437452516608_aca888b6-b886-4211-997c-657687c17a81.png">>, c
ause:{invalid_ref,#Ref<0.0.0.120551>}
[W]     storage_0@127.0.0.1     2015-12-10 17:35:50.648050 +0800        1449740150      leo_storage_handler_object:read_and_repair_2/3  935     key:<<"images/upload/zhiku/file/1449197962149_bfca0ce7-cdab-456a-a3b0-021ed42c5e56.jpg">>, cause:{inva
lid_ref,#Ref<0.0.0.120551>}
[W]     storage_0@127.0.0.1     2015-12-10 17:35:50.649093 +0800        1449740150      leo_storage_handler_object:read_and_repair_2/3  935     key:<<"images/upload/zhiku/titleImage/1448604621162_f0f88e32-74b3-4a1a-a631-1a3c60a96d50.jpg">>, cause
:{invalid_ref,#Ref<0.0.0.120551>}
[E] 

I don't know why leofs to start storage_1,in fact I just storage_0. It's start failed ,at same time,there is begin to can't load file.

**Comment by yosukehara** [comment]
You're not able to add another storage node because you already configured **total replicas = 1**.
LeoFS does not support reconfigured a consistency level.

If you want to migrate your LeoFS to new one which is a clustered Leo's storage - *total replicas is 2 and more*, you retrieve all objects from the current LeoFS, then put them to new one.

**Comment by weiransoft** [comment]
Yes , you are right,I think that is my misunderstanding .

**Comment by yosukehara** [comment]
I'm going to close this issue.
