### ISSUE TITLE
Unable to use subnet masks within IPs for NFS keys

### ISSUE THREAD

**Issue by tonyhb** [leo-project/leo_gateway#63]
You can't currently assign NFS keys via `gen-nfs-mnt-key` as `10.1.1.0/24`.  It would be good to be able generate a key for a range of IPs so that, for example, docker containers generated within a particular subnet can use a specific key.

**Comment by mocchira** [comment]
@tonyhb thank you for reporting.
As we've managed all issues about leofs at https://github.com/leo-project/leofs/issues
I moved this one to https://github.com/leo-project/leofs/issues/571.
please follow the above link for subsequent discussion.
